### PR TITLE
Added --all-disk option

### PR DESCRIPTION
**Pull request by GaryCarneiro**

### CODE REVIEW

**Comment by nihlaeth** [comment]
I put your pull request in the ps/3 branch and made some minor changes to it. There were some formatting issues (2 space indents instead of 4). I also chopped up some long lines and renamed a few variables. To be fair, the rest of the code isn't at all up to standard, but I like new code to be so there's less cleanup work later on.

Edit: never mind, this is not a problem with your code, but the old code! My bad.
~~One thing I miss is error checking for your all-disk option; now, if it doesn't find any disks that smartmon can work with, it simply says list index out of range. This can happen if the disk does not support smart, or the regex does not recognize the disk (for examle if they are named vd[a-z]). Again, the original code doesn't do this either, so maybe we can leave this until I find time to do a major rewrite.~~

Thanks for your contribution!

**Comment by GaryCarneiro** [comment]
@nihlaeth 
Thank you for putting your code on GitHub. It helped me to get something quickly done.

I coded this quick and dirty for an urgent requirement. Given enough time we can work on this and clean it up as per code styling guide. Thanks for looking and cleaning up  my code. 

If you have any new ideas, we can work on fixing it.

Regards
Garfield Carneiro

**Comment by nihlaeth** [comment]
@GaryCarneiro
I did a major rewrite only a few days ago, so most is cleaned up now, though I'm always up for improving further.

You might want to check out my changes, it now not only parses smartmontools output, it also interprets the exit code, so it catches a lot more warning and failure signals.

**Comment by GaryCarneiro** [comment]
I got bored and rewrote the whole check using a new logic

https://github.com/GaryCarneiro/Nagios_check_smartmon/blob/master/check_smartmon_alldisk.py

On Mon, Feb 29, 2016 at 1:21 AM, Nihlaeth notifications@github.com wrote:

> @GaryCarneiro https://github.com/GaryCarneiro
> I did a major rewrite only a few days ago, so most is cleaned up now,
> though I'm always up for improving further.
> 
> You might want to check out my changes, it now not only parses
> smartmontools output, it also interprets the exit code, so it catches a lot
> more warning and failure signals.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nihlaeth/Nagios_check_smartmon/pull/3#issuecomment-190118505
> .

## 

Garfield Carneiro

**Comment by nihlaeth** [comment]
That should prevent the crypt/lv/raid issues, if you'd expand the valid disk regex a little. But it only checks the health status, and there are a lof failure indicators that don't show up in the form of a failed health status. Why not use the check_smartmon.py script to go over the list of disks that check_smartmon_alldisk provides?

**Pull request merged**
